### ISSUE TITLE
review pre-BlueSky tomography data collection procedures

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/APS_BlueSky_tools#10]
Examine the existing data collection procedures used by APS tomography for algorithm and metadata.  Incorporate where possible in #8.

**Comment by MarkRivers** [comment]
Pete, I have implemented on-the-fly tomography scanning which our users are pretty happy with.  I have an IDL implementation (in production) and a Python version (tested but not in production).  I would be interested to discuss with you, since if you come up with a nice Python implementation I would be interested in using it.  The problems I think are in how to abstract the very device-dependent nature of hardware triggered fly scans.

**Comment by prjemian** [comment]
completed as part of 2-BM-B beam time prep (https://github.com/APS-2BM-MIC/ipython-user2bmb/issues/1)
