### ISSUE TITLE
EPICS area detector support in BlueSky

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/APS_BlueSky_tools#9]
How to get info (and/or data) from each new frame into BlueSky stream?

Current ophyd support was built around earlier AD version.  The API has changed and that support fails.

**Comment by prjemian** [comment]
This PV, `13SIM1:image1:UniqueId_RBV` updates with each new frame.  Is that the best one on which to rely?

**Comment by prjemian** [comment]
This PV, ``13SIM1:cam1:NumImagesCounter_RBV`` is another choice.  This PV starts from `0` each time `13SIM1:cam1:Acquire` is pressed (set to 1).  The *UniqueId* PV increments and is only reset by a CA client.

**Comment by prjemian** [comment]
These are identical it seems:
* `13SIM1:cam1:ArrayCounter_RBV`
* `13SIM1:image1:UniqueId_RBV`

**Comment by prjemian** [comment]
Basic strategy:

* configure area detector for image plugin
* set `PV.read_attrs = ['cam']`
* set `PV.cam.read_attrs = ['array_counter']`
* in streaming (0MQ) callback, send array_counter.value and image when stream provides new value

**Comment by prjemian** [comment]
This is the AD setup (attn @mdwyman):

    from ophyd import SingleTrigger, SimDetector, ImagePlugin

    class MyPlainSimDetector(SimDetector, SingleTrigger):
        image = Component(ImagePlugin, suffix="image1:")

    plainsimdet = MyPlainSimDetector('13SIM1:', name='plainsimdet')
    plainsimdet.read_attrs = ['cam']
    # https://github.com/BCDA-APS/APS_BlueSky_tools/issues/9
    plainsimdet.cam.read_attrs = ['array_counter']

**Comment by prjemian** [comment]
This is what happens when the detector is *read* in BlueSky in ipython session:

```
In [23]: plainsimdet.read()
Out[23]: 
OrderedDict([('plainsimdet_cam_array_counter',
              {'timestamp': 1512578603.690354, 'value': 316})])
```

**Comment by prjemian** [comment]
An example is from the sender code:

```
def mona_zmq_sender(sender, key, document, detector):
    '''
    send documents from BlueSky events for the MONA project via a ZMQ pair
    
    This code is called from a BlueSky callback
    
    EXAMPLE::
    
        from ophyd import SingleTrigger, SimDetector, ImagePlugin
        from APS_BlueSky_tools.zmq_pair import ZMQ_Pair, mona_zmq_sender
        
        class MyPlainSimDetector(SimDetector, SingleTrigger):
            image = Component(ImagePlugin, suffix="image1:")

        class MonaCallback0MQ(object):
           """
           My BlueSky 0MQ talker to send *all* documents emitted
           """
           
           def __init__(self, host=None, port=None, detector=None):
               self.talker = ZMQ_Pair(host or "localhost", port or "5556")
               self.detector = detector
           
           def end(self):
               """ZMQ client tells the server to end the connection"""
               self.talker.end()
        
           def receiver(self, key, document):
               """receive from RunEngine, send from 0MQ talker"""
               mona_zmq_sender(self.talker, key, document, self.detector)
       
        zmq_talker = MonaCallback0MQ(detector=plainsimdet.image)
        RE.subscribe(zmq_talker.receiver)
        adsimple = MyPlainSimDetector('13SIM1:', name='adsimple')
        adsimple.read_attrs = ['cam']
        RE(bp.count([adsimple], num=2))
        RE(bp.count([adsimple], num=5))
        zmq_talker.end()
    
    '''
    import json
    sender.send_string(key)
    sender.send_string(json.dumps(document))
    if key == "event" and detector is not None:
        # Is it faster to pick this up by EPICS CA?
        # Using 0MQ, no additional library is needed
        image = detector.image
        sender.send_string("image")
        sender.send_string(str(image.shape))
        sender.send_string(str(image.dtype))
        sender.send(image)
```

**Comment by prjemian** [comment]
For context, see:

* https://github.com/BCDA-APS/APS_BlueSky_tools/blob/master/APS_BlueSky_tools/zmq_pair.py
* https://github.com/prjemian/ookhd_ipython_profile_bluesky/blob/master/startup/80-callbacks.py

**Comment by MarkRivers** [comment]
>These are identical it seems:
13SIM1:cam1:ArrayCounter_RBV
13SIM1:image1:UniqueId_RBV

No, they are not identical.  On some detectors UniqueId comes from the hardware.  On other detectors it is a software counter in the driver.  It cannot be modified by clients.

ArrayCounter_RBV can be reset by writing to ArrayCounter from a client.

The [Release.md for ADViewers R1-0 ](https://github.com/areaDetector/ADViewers/blob/master/RELEASE.md) says the following:

>Previously this ImageJ plugin monitored the UniqueId_RBV PV in the NDPluginStdArrays plugin, and read the new image from this plugin when UniqueId_RBV changed.
However, this does not work correctly with the new ProcessPlugin feature in NDPluginDriver, because that does not increment the UniqueId. EPICS_AD_Viewer.java was changed so that it now monitors the ArrayCounter_RBV PV in NDPluginStdArrays rather than UniqueId_RBV. ArrayCounter_RBV will increment every time the plugin receives a new NDArray, which fixes the problem.
Note that ArrayCounter_RBV will also change if the user manually changes ArrayCounter, for example by setting it back to 0. This will also cause ImageJ to display the image, when it would not have done so previously. This should not be a problem.

Thus I would suggest that you monitor 13SIM1:image1:ArrayCounter_RBV (not cam1: as you said because that will update even if the image1: plugin is disabled or is only processing a subset of NDArrays.

**Comment by MarkRivers** [comment]
If I were embarking on this project today I would seriously consider using pvAccess rather than Channel Access to get the data into BlueSky.  If you do so you can get the entire NTNDArray atomically, and you get all of the NDArray attributes, not just the image data. 

pvaPy provides a Python interface to pvAccess.  

areaDetector builds with pvAccess out of the box, both with 3.15 and EPICS 7.0.1.  There is already an ImageJ viewer that uses pvAccess, and I encourage its use as well.

The following is a trivial Python program to read NTNDArray data in Python using pvAccess that Sinisa sent me this week.
```
#!/usr/bin/env python

import time
import pvaccess
from pvaccess import Channel
from pvaccess import PvObject

class SrfbMonitor:

    def __init__(self):
        self.nReceivedArrays = 0

    def process(self, pv):
        self.nReceivedArrays += 1
        arrayId = pv['uniqueId']
        floatArray = pv['value'][0]['floatValue']
        sum = floatArray.sum()
        if self.nReceivedArrays % 100 == 0:
            print('NTNDArray id %s sum: %s' % (arrayId, sum))
        return

if __name__ == '__main__':
    c = Channel('srfb_ndarray')
    srfbMonitor = SrfbMonitor()
    c.subscribe('process', srfbMonitor.process)
    c.startMonitor('')
    time.sleep(120)
    c.stopMonitor()
    c.unsubscribe('process')

```
pvAccess has many advantages:
- You can retrieve the native NDArrray data type without having to converted to a fixed data type waveform record.
- No need to worry about EPICS_CA_MAX_ARRAY_BYTES
- You have access to all fields of the NDArray, including attributes, timestamps, etc.

**Comment by MarkRivers** [comment]
> Current ophyd support was built around earlier AD version. The API has changed and that support fails.

I am curious what changed in the API to break ophyd?

**Comment by prjemian** [comment]
The EPICS AreaDetector interface is part of [ophyd](https://github.com/NSLS-II/ophyd/tree/master/ophyd/areadetector).  I'm going to leave integration of pvAccess into ophyd to the NSLS-II team for now (attn: @tacaswell, @danielballan)

As I understand it, ophyd uses pyepics to access EPICS3 PVs.  Recent work on ophyd might enable other interfaces such as pvaPy to access EPICS4 (or possibly EPICS7) structures.

What changed in the API (as I remember) was the HDF5 plugin in AreaDetector.  The first step is [testing against multiple versions of EPICS and AreaDetector](https://github.com/NSLS-II/ophyd/issues/459).  That testing will reveal any relevant problems.

**Comment by danielballan** [comment]
PVA integration is not on our immediate roadmap, but it is on our radar, and we have played with what ophyd integration might look like. We aim to avoid boxing ourselves in in any way that would make PVA integration more difficult in the future. I agree that the improvements it provides for N-dimensional array data are compelling.

We haven't pinned down what is causing newer versions of AD to break ophyd yet, but as @prjemian noted we are working on testing against a matrix of EPICS / AD versions, and that will clear things up. Most beamlines at NSLS-II are running AD 1.9.x, and it would be reasonable if AD 2.x introduced breaking changes.

**Comment by MarkRivers** [comment]
Beginning with ADCore R2-2 there is a PV that clients can use to determine which version of ADCore the IOC is built with: $(P)$(R)ADCoreVersion_RBV.  This is available for all drivers and plugins.  If this PV does not exist then the IOC is R2-1 or earlier.  I suspect most NSLS-II IOCs are either R1-X or R2-2 or higher.  

For drivers there is another PV $(P)$(R)DriverVersion_RBV that gives the driver version, as shown in this screen shot.
![image](https://user-images.githubusercontent.com/6115534/33690350-bcc8e6a4-daa8-11e7-9fa0-15851a3d11aa.png)

**Comment by prjemian** [comment]
The model that is working now creates an *EpicsSignal* for the `$(P)cam1:ArrayCounter_RBV` PV and *Monitor*s that signal during the scan.  When an event on that signal is received, that indicates a new image is ready.  The image and other data will be sent to the ZMQ pipe.
